logging:
  pattern:
    console: "[%date{YYYY/MM/dd HH:mm:ss:SSS}] %clr([${PID:- }]){magenta} -- %clr([%level]){green} [%thread] %clr([%logger{10}:%line]){cyan} : %msg%n"
  level:
    #org.hibernate: trace
    org.hibernate.SQL: debug
    org.springframework.jdbc.core.JdbcTemplate: debug
    #org.springframework.transaction: trace